# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-05-04 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=60)),
                ('autor', models.CharField(max_length=40)),
                ('fecha_publicacion', models.DateField()),
                ('foto_portada', models.URLField()),
                ('descripcion', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=1)),
                ('comentarios', models.TextField()),
                ('genero', models.CharField(choices=[('D', 'Drama'), ('T', 'Terror')], max_length=16)),
            ],
        ),
    ]
